### ISSUE TITLE
Worries on Catalina

### ISSUE THREAD

**Issue by Arubinu** [barneygale/elevate#9]
Hello,

This module looks very interesting, but it does not work on MacOS Catalina unfortunately.

Do you have a solution?

**Comment by barneygale** [comment]
If you run this from terminal, what happens?

```
do shell script "echo hello" with administrator privileges
```

**Comment by Arubinu** [comment]
The window requesting the fingerprint opens and nothing happens.

I used this osascript command too but from Catalina it doesn't
 does not work anymore.

According to the internet it would be a Sandbox fashion problem !?

**Comment by barneygale** [comment]
Stack trace + terminal output from the example in the readme would be useful.

**Comment by Arubinu** [comment]
`osascript -e 'do shell script "echo hello" with administrator privileges'`:
```
hello
```

Using `elevate()`:
```
0:143: execution error: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7: can't find '__main__' module in '.'
 (1)
```

With the example of README:
```
before  False
0:182: execution error: /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'test-elevate.py': [Errno 1] Operation not permitted
 (2)
```

**Comment by mightymercado** [comment]
I tested on Catalina and it worked fine but I used 3.6.9. Maybe, it's a version issue. Trying rolling back.

**Comment by Arubinu** [comment]
Thank you for your comment @mightymercado .

I tried with Python 3.6.8, but the problem remains the same and it's normal.
MacOS has changed for more security :/

**Comment by mightymercado** [comment]
@Arubinu Ah, I just realized. While I'm on Catalina, I didn't actually use the default Python binaries from homebrew. Due to my use case, I wanted to produce binaries that are backwards compatible with older Mac OS versions, I built a Python image from source with Developer Tools from Mountain Lion (10.8). This is probably the reason why ` elevate()` still works for me.  To solve your problem, follow the instructions [here](https://gist.github.com/phfaist/a5b8a895b003822df5397731f4673042) to build Python for an older Mac, then elevate() should start working again... Alternatively, you could just build on a Mac that's older then run on a different machine with Catalina.

**Comment by Arubinu** [comment]
I understand better. Thanks for this solution.
